/**
 * IKEA catalog — the swappable "real furniture" layer.
 *
 * Styles and room types are static config. The IKEA products now live in
 * Postgres (ikea_products): SEED_PRODUCTS below is the seed source, pushed into
 * the table by seedIkeaProducts() on server boot, and every product read goes
 * through the database. When a live IKEA product API lands, replace the seed
 * (or seedIkeaProducts) — the table, read helpers, routes, and client are
 * unaffected.
 */

import { db, ikeaProductsTable } from "@workspace/db";
import { and, arrayContains, inArray, ne, sql } from "drizzle-orm";

import ikeaSeed from "./ikeaSeed.json";

export interface StylePreset {
  id: string;
  name: string;
  tagline: string;
  description: string;
  accentColor: string;
  previewImage: string;
  /** Internal-only direction passed to the image model. Not exposed via the API. */
  promptHint: string;
}

export interface RoomType {
  id: string;
  name: string;
  description: string;
}

export interface Product {
  id: string;
  name: string;
  category: string;
  color: string;
  price: number;
  currency: string;
  /** Room type ids this product is eligible for. */
  roomTypes: string[];
  /** Functional role in the room (e.g. sofa, bed, rug), used for de-cluttered selection. */
  role: string;
  /** Broad category bucket (e.g. Lighting, Seating, Storage) for high-level swap filtering. */
  group: string;
  imageUrl: string;
  buyUrl: string;
}

const STYLE_DATA: StylePreset[] = [
  {
    id: "cozy",
    name: "Cozy",
    tagline: "Warm, layered, hygge",
    description:
      "Soft textures, warm wood tones, and gentle lighting that make a room feel like a hug.",
    accentColor: "#C77B4A",
    previewImage: "/api/assets/styles/cozy.png",
    promptHint:
      "Warm, inviting hygge atmosphere with soft textures, warm wood tones, layered textiles, and gentle ambient lighting.",
  },
  {
    id: "dark",
    name: "Dark",
    tagline: "Moody and refined",
    description:
      "Deep charcoals, rich woods, and dramatic low lighting for a sophisticated, grounded feel.",
    accentColor: "#3A3D44",
    previewImage: "/api/assets/styles/dark.png",
    promptHint:
      "Moody, sophisticated dark palette with deep charcoals, rich dark woods, dramatic low lighting, and a refined feel.",
  },
  {
    id: "white",
    name: "White",
    tagline: "Bright Scandinavian",
    description:
      "Crisp whites, light woods, and clean lines that flood the space with calm, airy light.",
    accentColor: "#8AA395",
    previewImage: "/api/assets/styles/white.png",
    promptHint:
      "Bright, airy Scandinavian minimalism with crisp whites, light woods, clean lines, and abundant natural light.",
  },
  {
    id: "modern",
    name: "Modern",
    tagline: "Sleek and contemporary",
    description:
      "Clean geometry, muted tones, and premium materials for an uncluttered, contemporary look.",
    accentColor: "#4C6B6F",
    previewImage: "/api/assets/styles/modern.png",
    promptHint:
      "Sleek contemporary design with clean geometry, muted tones, premium materials, and uncluttered sophistication.",
  },
];

/**
 * Room types drive product selection. A redesign is grounded in a de-cluttered
 * set of pieces chosen for the chosen room (see getProductsForRoom).
 */
const ROOM_DATA: RoomType[] = [
  {
    id: "living-room",
    name: "Living Room",
    description: "Sofa, coffee table, and layered lighting for a shared space.",
  },
  {
    id: "bedroom",
    name: "Bedroom",
    description: "Bed, nightstand, and storage for a restful retreat.",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    description: "Bar stools, open shelving, and a cart for a functional cook space.",
  },
  {
    id: "dining-room",
    name: "Dining Room",
    description: "Table, chairs, and a pendant for gathering over meals.",
  },
  {
    id: "home-office",
    name: "Home Office",
    description: "Desk, chair, and storage for a focused workspace.",
  },
];

/**
 * Seed source for the ikea_products table: real IKEA US products. These are the
 * pool the image model draws from; for any given redesign a de-cluttered subset
 * is selected per room (one piece per functional role, capped). Prices in USD.
 *
 * seedIkeaProducts() upserts these into Postgres on boot. When the live IKEA
 * product API lands, replace this array (or seedIkeaProducts) — nothing else in
 * the route or client should need to change.
 */
/**
 * Seed source for the ikea_products table: real IKEA US products, generated by
 * the ingestion script (scripts/src/ingestIkea.ts) from IKEA's public search
 * endpoint and stored as ikeaSeed.json. seedIkeaProducts() upserts these into
 * Postgres on boot. To refresh the catalog, re-run the ingestion script; to
 * swap in a live IKEA product API later, change only the seed source.
 */
export const SEED_PRODUCTS: Product[] = ikeaSeed as Product[];

/**
 * Per-room functional role priority. Selection walks this list in order, picks
 * the first eligible product per role, and caps the result — keeping the redesign
 * (and its shoppable tags) de-cluttered and believable for the room.
 */
const ROOM_ROLE_PRIORITY: Record<string, string[]> = {
  "living-room": [
    "sofa",
    "coffee-table",
    "rug",
    "floor-lamp",
    "accent-seating",
    "bookcase",
    "pendant",
  ],
  bedroom: ["bed", "nightstand", "dresser", "table-lamp", "rug", "floor-lamp"],
  kitchen: ["bar-stool", "open-shelf", "pendant", "cart"],
  "dining-room": ["dining-table", "dining-chair", "pendant", "rug"],
  "home-office": ["desk", "office-chair", "shelving", "task-lamp", "drawer-unit"],
};

const MAX_PRODUCTS_PER_ROOM = 5;

/** Public style list (without internal prompt hints). */
export function listStyles(): Omit<StylePreset, "promptHint">[] {
  return STYLE_DATA.map(({ promptHint: _promptHint, ...rest }) => rest);
}

export function getStyle(styleId: string): StylePreset | undefined {
  return STYLE_DATA.find((s) => s.id === styleId);
}

export function listRooms(): RoomType[] {
  return ROOM_DATA;
}

export function getRoom(roomTypeId: string): RoomType | undefined {
  return ROOM_DATA.find((r) => r.id === roomTypeId);
}

/**
 * Idempotently seeds the ikea_products table from SEED_PRODUCTS. Runs on server
 * boot; on conflict it refreshes every field so catalog edits propagate without
 * a manual migration. This is the one place the static seed touches the DB —
 * all reads below go through Postgres.
 */
export async function seedIkeaProducts(): Promise<void> {
  if (SEED_PRODUCTS.length === 0) return;
  // Chunk the upsert: with ~1000 rows x 11 columns we'd otherwise blow past
  // Postgres' bind-parameter limit (65535) in a single statement.
  const CHUNK_SIZE = 500;
  for (let i = 0; i < SEED_PRODUCTS.length; i += CHUNK_SIZE) {
    const chunk = SEED_PRODUCTS.slice(i, i + CHUNK_SIZE);
    await db
      .insert(ikeaProductsTable)
      .values(chunk)
      .onConflictDoUpdate({
        target: ikeaProductsTable.id,
        set: {
          name: sql`excluded.name`,
          category: sql`excluded.category`,
          color: sql`excluded.color`,
          price: sql`excluded.price`,
          currency: sql`excluded.currency`,
          roomTypes: sql`excluded.room_types`,
          role: sql`excluded.role`,
          group: sql`excluded."group"`,
          imageUrl: sql`excluded.image_url`,
          buyUrl: sql`excluded.buy_url`,
        },
      });
  }
}

/**
 * Returns the full active product catalog from the database. Kept for the
 * /products endpoint and forward compatibility; selection for a redesign goes
 * through getProductsForRoom.
 */
export async function getProductsForStyle(_styleId?: string): Promise<Product[]> {
  // Ordered by id so the catalog (and any first-match selection over it) is
  // deterministic across requests and environments.
  return db.select().from(ikeaProductsTable).orderBy(ikeaProductsTable.id);
}

/**
 * All products eligible for a room (the full swappable pool), regardless of the
 * de-cluttered default selection. Powers the result screen's "swap" picker,
 * where the user can replace a curated piece with any other eligible product.
 *
 * Uncategorized items (role "other") are excluded: they have no functional slot,
 * so they should neither fill the de-cluttered default nor appear as swap
 * candidates. Ordered by id for deterministic first-per-role selection.
 */
export async function getEligibleProductsForRoom(
  roomTypeId: string,
): Promise<Product[]> {
  return db
    .select()
    .from(ikeaProductsTable)
    .where(
      and(
        arrayContains(ikeaProductsTable.roomTypes, [roomTypeId]),
        ne(ikeaProductsTable.role, "other"),
      ),
    )
    .orderBy(ikeaProductsTable.id);
}

/**
 * Resolves an explicit, user-curated list of product ids to real products,
 * preserving the given order and dropping any unknown ids. Used when the user
 * has curated their pieces on the result screen and asks to regenerate.
 */
export async function getProductsByIds(ids: string[]): Promise<Product[]> {
  if (ids.length === 0) return [];
  const rows = await db
    .select()
    .from(ikeaProductsTable)
    .where(inArray(ikeaProductsTable.id, ids));
  const byId = new Map(rows.map((p) => [p.id, p]));
  const result: Product[] = [];
  for (const id of ids) {
    const match = byId.get(id);
    if (match) result.push(match);
  }
  return result;
}

/**
 * Pure de-clutter logic over an already-fetched eligible pool: picks one piece
 * per functional role, ordered by the room's role priority and capped at
 * MAX_PRODUCTS_PER_ROOM. Extracted as a pure function so it stays unit-testable
 * without a database. Optionally narrows to a user-chosen subset; if the filter
 * would leave nothing, the full default selection is returned so a redesign is
 * never grounded in zero products.
 */
export function selectDecluttered(
  eligible: Product[],
  roomTypeId: string,
  selectedProductIds?: string[],
): Product[] {
  const byRole = new Map<string, Product>();
  for (const p of eligible) {
    if (!byRole.has(p.role)) {
      byRole.set(p.role, p);
    }
  }

  const priority = ROOM_ROLE_PRIORITY[roomTypeId] ?? [];
  const ordered: Product[] = [];
  for (const role of priority) {
    const match = byRole.get(role);
    if (match) {
      ordered.push(match);
      byRole.delete(role);
    }
  }
  // Append any eligible roles not covered by the priority list (future-proofing).
  for (const remaining of byRole.values()) {
    ordered.push(remaining);
  }

  const defaultSelection = ordered.slice(0, MAX_PRODUCTS_PER_ROOM);

  if (!selectedProductIds || selectedProductIds.length === 0) {
    return defaultSelection;
  }

  const allowed = new Set(selectedProductIds);
  const filtered = defaultSelection.filter((p) => allowed.has(p.id));
  return filtered.length > 0 ? filtered : defaultSelection;
}

/**
 * Deterministically selects a de-cluttered set of products for a room from the
 * database: one piece per functional role, ordered by the room's role priority
 * and capped. Keeps the generated room — and the "Shop the look" tags overlaid
 * on it — accurate and uncluttered.
 */
export async function getProductsForRoom(
  roomTypeId: string,
  selectedProductIds?: string[],
): Promise<Product[]> {
  const eligible = await getEligibleProductsForRoom(roomTypeId);
  return selectDecluttered(eligible, roomTypeId, selectedProductIds);
}
